name = "UnreasonableComplicated"
author = "pen787"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "caffd03231caf36f6372435cb3f236020535e425416dea403a7bb71cf6b6852c"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"
