name = "UnreasonableComplicated"
author = "pen787"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "81ca592b524f259dff3c84585ed3f484601702b8770cf1db8c8e6cc667f61827"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"
