# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				chicken = true
				bee = true
				donkey = true
				cow = true
				slime = true
				pig = true
				skeleton = true
				bat = true
				rabbit = true
				zombie = true
				drowned = true
				sheep = true
				experience_orb = true
				player = true
				item = true
				wolf = true
				villager = true
				salmon = true
				zombie_villager = true
				goat = true
				horse = true
				phantom = true
				glow_squid = true
				witch = true
				cod = true
				glow_item_frame = false
				squid = true
				spider = true
				creeper = true
				enderman = true

			[light_sources.settings.entities.naturalist]
				deer = true
				snail = true
				canary = true
				firefly = true
				bluejay = true
				coral_snake = true
				snake = true
				cardinal = true
				robin = true
				bass = true
				butterfly = true
				bear = true
				lizard = true

